---
:verbose: true
:concurrency: <%= (ENV['MAX_THREADS'] || 10).to_i %>
:queues:
  - ["default", 10]
  - ["mailers", 10]

:pidfile: <%= ENV.fetch('RUN_PATH') { 'tmp/pids/' }%><%= ENV['RAILS_ENV'] %>_sidekiq.pid
